services:

  postgres:
    image: postgres:16
    container_name: homestay-pms-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: homestay_pms
      POSTGRES_USER: pms_user
      POSTGRES_PASSWORD: pms_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: