#spring.application.name=pms-backend
spring.application.name=homestay-pms

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/homestay_pms
spring.datasource.username=pms_user
spring.datasource.password=pms_password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

# Application timezone
spring.jackson.time-zone=Asia/Kolkata